## WARNING ##
# This file is auotmaticly generated, any changes
# will be overwritten.

##################################################
################  COMMON ENTITIES  ###############
##################################################

###############  input_boolean:  #################
input_boolean:
  garage_left_lock_notifications:
    name: garage_left Lock Notifications
  garage_left_dooraccess_notifications:
    name: garage_left Door Notifications
  garage_left_garageacess_notifications:
    name: garage_left Garage Notifications
  garage_left_reset_lock:
    name: garage_left reset lock

###################  script:  ####################
script:
  garage_left_reset_lock:
    sequence:
      - service: script.garage_left_manual_notify
        data_template:
          title: "reset"
          message: "garage_left"

  garage_left_reset_codeslot:
    mode: parallel
    fields:
      code_slot:
        description: The code slot to reset
        example: 1
    variables:
      # Constant used later to loop through day specific entities
      days: ['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat']
    sequence:
      - service: input_boolean.turn_off
        data_template:
          entity_id: "input_boolean.enabled_garage_left_{{ code_slot | string }}"
      - service: input_text.set_value
        data_template:
          entity_id: "input_text.garage_left_name_{{ code_slot | string }}"
          value: ""
      - service: input_text.set_value
        data_template:
          entity_id: "input_text.garage_left_pin_{{ code_slot | string }}"
          value: ""
      - service: input_boolean.turn_off
        data_template:
          entity_id: "input_boolean.notify_garage_left_{{ code_slot | string }}"
      - service: input_number.set_value
        data_template:
          entity_id: "input_number.accesscount_garage_left_{{ code_slot | string }}"
          value: "0"
      - service: input_datetime.set_datetime
        data_template:
          entity_id: "input_datetime.start_date_garage_left_{{ code_slot | string }}"
          date: >-
            {{ now().strftime('%Y-%m-%d') }}
      - service: input_datetime.set_datetime
        data_template:
          entity_id: "input_datetime.end_date_garage_left_{{ code_slot | string }}"
          date: >-
            {{ now().strftime('%Y-%m-%d') }} 
      - service: input_boolean.turn_off
        data_template:
          entity_id: "input_boolean.daterange_garage_left_{{ code_slot | string }}"
      - service: input_boolean.turn_off
        data_template:
          entity_id: "input_boolean.accesslimit_garage_left_{{ code_slot | string }}"
      - service: input_boolean.turn_off
        data_template:
          entity_id: "input_boolean.reset_codeslot_garage_left_{{ code_slot | string }}"
      # Loop through each day of the week and reset the entities related to each one
      - repeat:
          count: 7
          sequence:
            - service: input_datetime.set_datetime
              data_template:
                entity_id: "input_datetime.{{ days[repeat.index - 1] }}_start_date_garage_left_{{ code_slot | string }}"
                time: "{{ '00:00' | timestamp_custom('%H:%M') }}"
            - service: input_datetime.set_datetime
              data_template:
                entity_id: "input_datetime.{{ days[repeat.index - 1] }}_end_date_garage_left_{{ code_slot | string }}"
                time: "{{ '00:00' | timestamp_custom('%H:%M') }}"
            - service: input_boolean.turn_on
              data_template:
                entity_id: "input_boolean.{{ days[repeat.index - 1] }}_garage_left_{{ code_slot | string }}"
            - service: input_boolean.turn_on
              data_template:
                entity_id: "input_boolean.{{ days[repeat.index - 1] }}_inc_garage_left_{{ code_slot | string }}"

  garage_left_refreshnodeinfo:
    description:  'Send MQTT RefreshNodeInfo command'
    sequence:
      - service: system_log.write
        data_template:
          message: "garage_left_TEMPLATENUM started noderefreshinfo: {{ now() }}"
          level: debug  
      - service: mqtt.publish
        data:
          topic: 'OpenZWave/1/command/refreshnodeinfo/'
          payload: >-
            {% set node_id = state_attr('lock.garage_left','node_id') %}
            { "node": {{ node_id }} }
          retain: true
          
###################  automation:  ####################
automation:

  - alias: reset_codeslot_garage_left
    trigger:
      entity_id: input_boolean.reset_codeslot_garage_left_1,input_boolean.reset_codeslot_garage_left_2,input_boolean.reset_codeslot_garage_left_3,input_boolean.reset_codeslot_garage_left_4,input_boolean.reset_codeslot_garage_left_5,input_boolean.reset_codeslot_garage_left_6,input_boolean.reset_codeslot_garage_left_7,input_boolean.reset_codeslot_garage_left_8,input_boolean.reset_codeslot_garage_left_9,input_boolean.reset_codeslot_garage_left_10
      platform: state
      to: 'on'
    action:
      - service: script.garage_left_reset_codeslot
        data_template:
          code_slot: "{{ trigger.entity_id.split('_')[-1] }}"

  - alias: garage_left Lock Notifications
    trigger:
      platform: event
      event_type: keymaster_lock_state_changed
      event_data:
        lockname: garage_left
    condition:
      - condition: state
        entity_id: input_boolean.garage_left_lock_notifications
        state: "on"
    action:
      - service: script.garage_left_manual_notify
        data_template:
          title: garage_left
          message: "{{ trigger.event.data.action_text }}"

  - alias: garage_left User Notifications
    trigger:
      platform: event
      event_type: keymaster_lock_state_changed
      event_data:
        lockname: garage_left
    condition:
      - condition: template
        value_template: "{{ trigger.event.data.code_slot > 0 }}"
      - condition: template
        value_template: "{{ is_state('input_boolean.notify_garage_left_' + trigger.event.data.code_slot | string, 'on') }}"
    action:
      - service: script.garage_left_manual_notify
        data_template:
          title: garage_left
          message: "{{ trigger.event.data.action_text }} ({{ trigger.event.data.code_slot_name }})"

  - alias: "garage_left Door Open and Close"
    trigger:
      entity_id: binary_sensor.door_garage_left_homekit
      platform: state
    condition:
      - condition: state
        entity_id: "input_boolean.garage_left_dooraccess_notifications"
        state: "on"
      - condition: template
        value_template: "{{ trigger.from_state.state in ('on', 'off') and trigger.to_state.state in ('on', 'off') }}"
    action:
      - service: script.garage_left_manual_notify
        data_template:
          title: garage_left
          message: "{% if trigger.to_state.state == 'on' %}Door Opened{% else %}Door Closed{% endif %}"

  - alias: garage_left Changed Code
    trigger:
      entity_id: input_text.garage_left_pin_1,input_text.garage_left_pin_2,input_text.garage_left_pin_3,input_text.garage_left_pin_4,input_text.garage_left_pin_5,input_text.garage_left_pin_6,input_text.garage_left_pin_7,input_text.garage_left_pin_8,input_text.garage_left_pin_9,input_text.garage_left_pin_10
      platform: state
    condition:
      - condition: template
        value_template: >-
          {{
            is_state('input_boolean.garage_left_enabled_' + trigger.entity_id.split('_')[-1], 'on')
            and
            (trigger.from_state.state != trigger.to_state.state)
          }}
    action:
      - service: persistent_notification.create
        data_template:
          title: garage_left LOCK MANAGER
          message: >-
            {{ 'You changed the PIN for garage_left code slot ' + trigger.entity_id.split('_')[-1] + '. Please enable it in order to make it active.'}}
      - service: input_boolean.turn_off
        data_template:
          entity_id: >-
            {{ 'input_boolean.enabled_garage_left_' + trigger.entity_id.split('_')[-1] }}

  - alias: garage_left Reset
    trigger:
      entity_id: input_boolean.garage_left_reset_lock
      platform: state
      from: "off"
      to: "on"
    action:
      - service: script.garage_left_reset_lock
      - service: input_boolean.turn_off
        entity_id: input_boolean.garage_left_reset_lock

  - alias: garage_left Decrement Access Count
    trigger:
      platform: event
      event_type: keymaster_lock_state_changed
      event_data:
        lockname: garage_left
    condition:
      - condition: template
        # make sure decrementing access entries is enabled 
        value_template: "{{ is_state('input_boolean.accesslimit_garage_left_' + trigger.event.data.code_slot | string, 'on') }}"
      - condition: template
        # Check for Keypad Unlock code
        value_template: >-
          {{
            trigger.event.data.code_slot > 0
            and
            (trigger.event.data.action_code is undefined or trigger.event.data.action_code in (6, 19))
          }}
    action:
      - service: input_number.decrement
        data_template:
          entity_id: "{{ 'input_number.accesscount_garage_left_' + trigger.event.data.code_slot | string }}"
