title: System

views:
  - !include ui/system/overview.yaml
  - !include ui/system/network.yaml
  # - title: DeCONZ
  #   path: deconz
  #   panel: true
  #   cards:
  #     - type: iframe
  #       url: https://google.com
  - !include ui/system/zha.yaml
  - title: ZHA Visualization
    path: zha-map
    panel: true
    cards:
      - type: 'custom:zha-network-visualization-card'

button_card_templates: !include_dir_merge_named ui/templates_button
# decluttering_templates: !include_dir_merge_named lovelace/decluttering

# resources:
  # - url: /hacsfiles/button-card/button-card.js
    # type: module
  # # - url: /hacsfiles/decluttering-card/decluttering-card.js
    # # type: module
  # - url: /hacsfiles/lovelace-card-mod/card-mod.js
    # type: module
  # - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
    # type: module
  # - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
    # type: module
  # - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
    # type: module
  # - url: /hacsfiles/roku-card/roku-card.js
    # type: module
  # - url: /hacsfiles/simple-thermostat/simple-thermostat.js
    # type: module
  # # - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
    # # type: js
  # # - url: /hacsfiles/vertical-style-card/vertical-style-card.js
    # # type: js
  # - url: /hacsfiles/weather-card/weather-card.js
    # type: module
