homeassistant:
  customize:
    binary_sensor.door_back_homekit:
      device_class: door
    binary_sensor.door_front_homekit:
      device_class: door
    binary_sensor.door_basement_homekit:
      device_class: door
    binary_sensor.door_garage_left_homekit:
      device_class: door
    binary_sensor.door_garage_right_homekit:
      device_class: door

input_select:
  abode_arm_mode:
    name: Alarm Auto Arm Mode
    options:
      - Perimeter & Motion
      - Perimeter (Doors/Windows)
      - "Off"
    icon: mdi:shield-refresh-outline

input_boolean:
  guest:
    name: Guest Mode
    icon: mdi:account

alarm_control_panel:
  - platform: manual
    name: HA
    arming_time: 0

