binary_sensor:
  - platform: mqtt
    name: "HAVM Connected"
    state_topic: "havm/lwt"
    value_template: "{{ value }}"
    payload_on: "online"
    payload_off: "offline"
    device_class: "connectivity"
    qos: 1
  - name: Ping HAVM
    platform: ping
    host: !secret ping_havm
