homeassistant:
  customize:
    binary_sensor.door_basement_coal:
      device_class: door
    binary_sensor.door_basement_dungeon:
      device_class: door
    binary_sensor.door_basement_inside:
      device_class: door
    binary_sensor.door_changing:
      device_class: door
    binary_sensor.door_dog_1x:
      device_class: door
    binary_sensor.door_dog_2x:
      device_class: door
    binary_sensor.door_guns:
      device_class: door
    binary_sensor.door_mbath:
      device_class: door
    binary_sensor.door_mbed:
      device_class: door
    binary_sensor.door_office_1x:
      device_class: door
    binary_sensor.door_office_2x:
      device_class: door
    binary_sensor.door_powder:
      device_class: door
    binary_sensor.door_private:
      device_class: door

light:
  ###### Template for Zigbee2MQTT light groups
  # - platform: mqtt
  #   schema: json
  #   name: MY_GROUP_NAME
  #   command_topic: "zigbee2mqtt/[GROUP_FRIENDLY_NAME]/set"
  #   state_topic: "zigbee2mqtt/[GROUP_FRIENDLY_NAME]"
  #   # Modify according to features supported by all devices in group
  #   color_temp: true
  #   brightness: true
  #   rgb: true
  - name: Basement Dungeon
    platform: mqtt
    schema: json
    command_topic: "zigbee2mqtt/Light Basement Dungeon/set"
    state_topic: "zigbee2mqtt/Light Basement Dungeon"
    brightness: true
  - name: GBath Vanity
    platform: mqtt
    schema: json
    command_topic: "zigbee2mqtt/Light GBath Vanity/set"
    state_topic: "zigbee2mqtt/Light GBath Vanity"
    brightness: true
  - name: Hall
    platform: mqtt
    schema: json
    command_topic: "zigbee2mqtt/Light Hall/set"
    state_topic: "zigbee2mqtt/Light Hall"
    brightness: true
  - name: MBath Closet
    platform: mqtt
    schema: json
    command_topic: "zigbee2mqtt/Light MBath Closet/set"
    state_topic: "zigbee2mqtt/Light MBath Closet"
    brightness: true
  - name: MBed Fan
    platform: mqtt
    schema: json
    command_topic: "zigbee2mqtt/Light MBed Fan/set"
    state_topic: "zigbee2mqtt/Light MBed Fan"
    brightness: true
    color_temp: true
    rgb: true
  - name: Porch
    platform: mqtt
    schema: json
    command_topic: "zigbee2mqtt/Light Porch/set"
    state_topic: "zigbee2mqtt/Light Porch"
    brightness: true
    color_temp: true
    rgb: true
  - name: Powder
    platform: mqtt
    schema: json
    command_topic: "zigbee2mqtt/Light Powder/set"
    state_topic: "zigbee2mqtt/Light Powder"
    brightness: true
