sensor:

  # Internet usage
  - platform: cox_sensor
    username: !secret cox_username
    password: !secret cox_password
  # https://github.com/dejanzelic/coxusage-docker
  # - platform: file
  #   name: Cox Usage
  #   file_path: /config/coxusage.json
  #   value_template: '{{ value_json.dumUsage }}'
  #   unit_of_measurement: GB
  # - platform: file
  #   name: Cox Limit
  #   file_path: /config/coxusage.json
  #   value_template: '{{ value_json.dumLimit }}'
  #   unit_of_measurement: GB
  # - platform: file
  #   name: Cox Utilization
  #   file_path: /config/coxusage.json
  #   value_template: '{{ value_json.dumUtilization }}'
  #   unit_of_measurement: '%'
  # - platform: file
  #   name: Cox Days Left
  #   file_path: /config/coxusage.json
  #   value_template: '{{ value_json.dumDaysLeft }}'
  #   unit_of_measurement: days

  # WAN IP
  # - platform: dnsip
  #   name: WAN IPv4
  # - platform: dnsip
  #   name: WAN IPv6
  #   ipv6: true
  
  # # Zeus
  # - platform: template
  #   sensors:
  #     zeus_net_in:
  #       friendly_name: Zeus Network In
  #       unit_of_measurement: Mbps
  #       value_template: "{{ (states('sensor.zeus_network_0_bps_received')|float/1000000)|round(2) }}"
  #       icon_template: mdi:download-network-outline
  #     zeus_net_out:
  #       friendly_name: Zeus Network Out
  #       unit_of_measurement: Mbps
  #       value_template: "{{ (states('sensor.zeus_network_0_bps_sent')|float/1000000)|round(2) }}"
  #       icon_template: mdi:upload-network-outline

