## WARNING ##
# This file is auotmaticly generated, any changes
# will be overwritten.

##################################################
################  COMMON ENTITIES  ###############
##################################################

###############  input_boolean:  #################
input_boolean:
  garage_right_lock_notifications:
    name: garage_right Lock Notifications
  garage_right_dooraccess_notifications:
    name: garage_right Door Notifications
  garage_right_garageacess_notifications:
    name: garage_right Garage Notifications
  garage_right_reset_lock:
    name: garage_right reset lock
  keymaster_garage_right_autolock:
    name: 'Auto Lock Enabled'
    icon: mdi:key-remove

###################  script:  ####################
script:
  keymaster_garage_right_reset_lock:
    sequence:
      - service: script.keymaster_garage_right_manual_notify
        data_template:
          title: "reset"
          message: "garage_right"

  keymaster_garage_right_reset_codeslot:
    mode: parallel
    fields:
      code_slot:
        description: The code slot to reset
        example: 1
    variables:
      # Constant used later to loop through day specific entities
      days: ['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat']
    sequence:
      - service: input_boolean.turn_off
        data_template:
          entity_id: "input_boolean.enabled_garage_right_{{ code_slot | string }}"
      - service: input_text.set_value
        data_template:
          entity_id: "input_text.garage_right_name_{{ code_slot | string }}"
          value: ""
      - service: input_text.set_value
        data_template:
          entity_id: "input_text.garage_right_pin_{{ code_slot | string }}"
          value: ""
      - service: input_boolean.turn_off
        data_template:
          entity_id: "input_boolean.notify_garage_right_{{ code_slot | string }}"
      - service: input_number.set_value
        data_template:
          entity_id: "input_number.accesscount_garage_right_{{ code_slot | string }}"
          value: "0"
      - service: input_datetime.set_datetime
        data_template:
          entity_id: "input_datetime.start_date_garage_right_{{ code_slot | string }}"
          datetime: >-
            {{ now().strftime('%Y-%m-%d 00:00') }}
      - service: input_datetime.set_datetime
        data_template:
          entity_id: "input_datetime.end_date_garage_right_{{ code_slot | string }}"
          datetime: >-
            {{ now().strftime('%Y-%m-%d 00:00') }}
      - service: input_boolean.turn_off
        data_template:
          entity_id: "input_boolean.daterange_garage_right_{{ code_slot | string }}"
      - service: input_boolean.turn_off
        data_template:
          entity_id: "input_boolean.accesslimit_garage_right_{{ code_slot | string }}"
      - service: input_boolean.turn_off
        data_template:
          entity_id: "input_boolean.reset_codeslot_garage_right_{{ code_slot | string }}"
      # Loop through each day of the week and reset the entities related to each one
      - repeat:
          count: 7
          sequence:
            - service: input_datetime.set_datetime
              data_template:
                entity_id: "input_datetime.{{ days[repeat.index - 1] }}_start_date_garage_right_{{ code_slot | string }}"
                time: "{{ '00:00' | timestamp_custom('%H:%M') }}"
            - service: input_datetime.set_datetime
              data_template:
                entity_id: "input_datetime.{{ days[repeat.index - 1] }}_end_date_garage_right_{{ code_slot | string }}"
                time: "{{ '00:00' | timestamp_custom('%H:%M') }}"
            - service: input_boolean.turn_on
              data_template:
                entity_id: "input_boolean.{{ days[repeat.index - 1] }}_garage_right_{{ code_slot | string }}"
            - service: input_boolean.turn_on
              data_template:
                entity_id: "input_boolean.{{ days[repeat.index - 1] }}_inc_garage_right_{{ code_slot | string }}"

  keymaster_garage_right_refreshnodeinfo:
    description:  'Send MQTT RefreshNodeInfo command'
    sequence:
      - service: system_log.write
        data_template:
          message: "garage_right_TEMPLATENUM started noderefreshinfo: {{ now() }}"
          level: debug  
      - service: mqtt.publish
        data:
          topic: 'OpenZWave/1/command/refreshnodeinfo/'
          payload: >-
            {% set node_id = state_attr('lock.garage_right','node_id') %}
            { "node": {{ node_id }} }
          retain: true

  keymaster_garage_right_start_timer_retry:
    sequence:
      - condition: state
        entity_id: lock.garage_right
        state: 'unlocked'
      - service: timer.cancel
        entity_id:  timer.keymaster_garage_right_autolock
      - service: timer.start
        data_template:
          entity_id: timer.keymaster_garage_right_autolock
          duration: 00:00:30

  keymaster_garage_right_start_timer:
    sequence:
      - condition: state
        entity_id: lock.garage_right
        state: 'unlocked'
      - service: timer.cancel
        entity_id:  timer.keymaster_garage_right_autolock
      - service: timer.start
        data_template:    # if next_dusk happens sooner than next_dawn, then it's daylight
          entity_id: timer.keymaster_garage_right_autolock
          duration: >
            {% if (((as_timestamp(states.sun.sun.attributes.next_dusk)) > (as_timestamp(states.sun.sun.attributes.next_dawn)))) %}
              {{ states('input_text.keymaster_garage_right_autolock_door_time_night')}}
            {% else %}
              {{ states('input_text.keymaster_garage_right_autolock_door_time_day')}}
            {% endif %}
          
###################  automation:  ####################
automation:

  - alias: garage_right Reset Code Slot
    trigger:
      entity_id: input_boolean.reset_codeslot_garage_right_1,input_boolean.reset_codeslot_garage_right_2,input_boolean.reset_codeslot_garage_right_3,input_boolean.reset_codeslot_garage_right_4,input_boolean.reset_codeslot_garage_right_5,input_boolean.reset_codeslot_garage_right_6,input_boolean.reset_codeslot_garage_right_7,input_boolean.reset_codeslot_garage_right_8,input_boolean.reset_codeslot_garage_right_9,input_boolean.reset_codeslot_garage_right_10
      platform: state
      to: 'on'
    action:
      - service: script.keymaster_garage_right_reset_codeslot
        data_template:
          code_slot: "{{ trigger.entity_id.split('_')[-1] }}"

  - alias: garage_right Lock Notifications
    trigger:
      platform: event
      event_type: keymaster_lock_state_changed
      event_data:
        lockname: garage_right
    condition:
      - condition: state
        entity_id: input_boolean.garage_right_lock_notifications
        state: "on"
    action:
      - service: script.keymaster_garage_right_manual_notify
        data_template:
          title: garage_right
          message: "{{ trigger.event.data.action_text }} {% if trigger.event.data.code_slot > 0 %}({{ trigger.event.data.code_slot_name }}){% endif %}"

  - alias: garage_right User Notifications
    trigger:
      platform: event
      event_type: keymaster_lock_state_changed
      event_data:
        lockname: garage_right
    condition:
      - condition: template
        value_template: "{{ trigger.event.data.code_slot > 0 }}"
      - condition: template
        value_template: "{{ is_state('input_boolean.notify_garage_right_' + trigger.event.data.code_slot | string, 'on') }}"
      - condition: state
        entity_id: input_boolean.garage_right_lock_notifications
        state: "off"
    action:
      - service: script.keymaster_garage_right_manual_notify
        data_template:
          title: garage_right
          message: "{{ trigger.event.data.action_text }} ({{ trigger.event.data.code_slot_name }})"

  - alias: garage_right Door Open and Close
    trigger:
      entity_id: binary_sensor.door_garage_right
      platform: state
    condition:
      - condition: state
        entity_id: "input_boolean.garage_right_dooraccess_notifications"
        state: "on"
      - condition: template
        value_template: "{{ trigger.from_state.state in ('on', 'off') and trigger.to_state.state in ('on', 'off') }}"
    action:
      - service: script.keymaster_garage_right_manual_notify
        data_template:
          title: garage_right
          message: "{% if trigger.to_state.state == 'on' %}Door Opened{% else %}Door Closed{% endif %}"

  - alias: garage_right Changed Code
    trigger:
      entity_id: input_text.garage_right_pin_1,input_text.garage_right_pin_2,input_text.garage_right_pin_3,input_text.garage_right_pin_4,input_text.garage_right_pin_5,input_text.garage_right_pin_6,input_text.garage_right_pin_7,input_text.garage_right_pin_8,input_text.garage_right_pin_9,input_text.garage_right_pin_10
      platform: state
    condition:
      - condition: template
        value_template: >-
          {{
            is_state('input_boolean.enabled_garage_right_' + trigger.entity_id.split('_')[-1], 'on')
            and
            (trigger.from_state.state != trigger.to_state.state)
          }}
    action:
      - service: persistent_notification.create
        data_template:
          title: garage_right LOCK MANAGER
          message: >-
            {{ 'You changed the PIN for garage_right code slot ' + trigger.entity_id.split('_')[-1] + '. Please enable it in order to make it active.'}}
      - service: input_boolean.turn_off
        data_template:
          entity_id: >-
            {{ 'input_boolean.enabled_garage_right_' + trigger.entity_id.split('_')[-1] }}

  - alias: garage_right Reset
    trigger:
      entity_id: input_boolean.garage_right_reset_lock
      platform: state
      from: "off"
      to: "on"
    action:
      - service: script.keymaster_garage_right_reset_lock
      - service: input_boolean.turn_off
        entity_id: input_boolean.garage_right_reset_lock

  - alias: garage_right Decrement Access Count
    trigger:
      platform: event
      event_type: keymaster_lock_state_changed
      event_data:
        lockname: garage_right
    condition:
      - condition: template
        # make sure decrementing access entries is enabled 
        value_template: "{{ is_state('input_boolean.accesslimit_garage_right_' + trigger.event.data.code_slot | string, 'on') }}"
      - condition: template
        # Check for Keypad Unlock code
        value_template: >-
          {{
            trigger.event.data.code_slot > 0
            and
            (trigger.event.data.action_code is undefined or trigger.event.data.action_code in (6, 19))
          }}
    action:
      - service: input_number.decrement
        data_template:
          entity_id: "{{ 'input_number.accesscount_garage_right_' + trigger.event.data.code_slot | string }}"

  - alias: keymaster_garage_right_locked
    trigger:
      entity_id: lock.garage_right
      platform: state
      to: locked
    action:
      - service: timer.cancel
        entity_id: timer.keymaster_garage_right_autolock
        
  - alias: keymaster_garage_right_unlocked
    trigger:
      entity_id: lock.garage_right
      platform: state
      to: unlocked
    condition:
      - condition: state
        entity_id: input_boolean.keymaster_garage_right_autolock
        state: "on"
    action:
      - service: script.turn_on
        entity_id: script.keymaster_garage_right_start_timer
      
  - alias: keymaster_garage_right_timer_finished
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.keymaster_garage_right_autolock
    action:
    - choose:
        - conditions:
            - condition: template
              value_template: "{{ (states('binary_sensor.door_garage_right') != 'on') }}"
          sequence:
            - service: lock.lock
              entity_id: lock.garage_right
        - conditions:
            - condition: template
              value_template: "{{ (states('binary_sensor.door_garage_right') == 'on') }}"
          sequence:
            - service: script.keymaster_garage_right_start_timer_retry
        
  - alias: keymaster_garage_right_disable_auto_lock
    trigger:
      entity_id: input_boolean.keymaster_garage_right_autolock
      platform: state
      to: 'off'
    action:
      - service: timer.cancel
        entity_id:
          - timer.keymaster_garage_right_autolock
      - service: lock.unlock
        entity_id: lock.garage_right
       
  - alias: keymaster_garage_right_enable_auto_lock
    trigger:
      entity_id: input_boolean.keymaster_garage_right_autolock
      platform: state
      to: 'on'
    action:
      - service: timer.cancel
        entity_id:
          - timer.keymaster_garage_right_autolock
      - service: lock.lock
        entity_id: lock.garage_right

###############  input_text:  #################
input_text:
  garage_right_lockname:
    initial: garage_right
    name: 'Lock Name'
  garage_right_garage_left_parent:
    initial: garage_left
    name: 'Parent lock'

  keymaster_garage_right_autolock_door_time_day:
    name: 'Day Auto Lock HH:MM:SS'
    initial: '00:15:00'
  keymaster_garage_right_autolock_door_time_night:
    name: 'Night Auto Lock HH:MM:SS'
    initial: '00:05:00'

###################  timer:  ####################
timer:
  keymaster_garage_right_autolock:
    name: 'Auto Lock Timer'
    